### ISSUE TITLE
Demo doesn't run on Safari

### ISSUE THREAD

**Issue by Beelal** [goinstant/webrtc#13]
https://webrtc.goinstant.com

![webrtc](https://f.cloud.github.com/assets/1430223/2380677/b4f9dbec-a8af-11e3-9bd6-5656b657431f.jpg)

**Comment by colinmacdonald** [comment]
WebRTC isn't supported in Safari. That being said, there is supposed to be an error message on the home screen when the browser is unsupported, will investigate that.

Thanks.

**Comment by colinmacdonald** [comment]
The supported code was commented out in the demo, fixed now.

https://webrtc.goinstant.com on safari or any unsupported browser should display an error on the home page now.
