### ISSUE TITLE
Warning:error : failed to fetch

### ISSUE THREAD

**Issue by macbroadcast** [goinstant/webrtc#19]
What do i need to modify in the brower /component to prevent this error  ?

...Warning:        error : failed to fetch https://raw.githubusercontent.com/discore/closest/0.1.2/component.json, got 404 "Not Found" Use --force to continue.
...

**Comment by colinmacdonald** [comment]
The `closest` dependency's account name changed from discore to tootallnate. Fixed: https://github.com/goinstant/webrtc/commit/250578241a4fd76ecd60ba3577a6c366be34ce67
