### ISSUE TITLE
WebRTC Launch

### ISSUE THREAD

**Issue by colinmacdonald** [goinstant/webrtc#4]
- [x] GoRTC docs
- [x] GoRTC open source template 
- [x] GoRTC deploy
- [x] WebRTC docs
- [x] WebRTC deploy
- [x] WebRTC demo autoStart option
- [x] WebRTC demo deploy
- [x] Register WebRTC and GoRTC with bower
- [x] Blog post
- [x] Add WebRTC demo to /examples page after the todo application
- [x] Review WebRTC github page
- [x] Review GoRTC github page

**Comment by byosko** [comment]
1. What will the URL for the demo be?
2. Can we get some kind of social sharing options on the demo? "This is cool! Share: Twitter, Google+" <-- @ntassone we should get this kind of thing on all demos.
3. Do we have a suitable image on the WebRTC widget docs that goes to the demo?

**Comment by ntassone** [comment]
1. I'll add this into the "powered by" footer that's on most of the demos.
2. Right now its just the screenshot of the widget, I can throw together an image as a CTA for the demo. We also need to add the "view code on github" button like we have on all the other widget's docs pages.

**Comment by byosko** [comment]
@ntassone I'm wondering if we should have a standard bar across the top of our demos, like we do with the Collab one?

The Collab one just goes to docs, but I'd rather it have the social sharing and signup on it vs. docs... or maybe all three is possible without overwhelming people.

**Comment by ntassone** [comment]
@byosko That's a good idea, I think it will work with all three. Then we can just include it on every demo we do so it stays consistent.

**Comment by byosko** [comment]
Yup. We would just need to write a custom message for the tweet button on each. Not sure how Google+ works, but I wouldn't mind adding it too.

**Comment by colinmacdonald** [comment]
The URL would just be something like webrtc-widget-demo.herokuapp.com.

I can format the webrtc docs to be the same as the collab-bundle https://developers.goinstant.com/v1/widgets/collaboration_bundle.html with a "try the demo" button.

**Comment by byosko** [comment]
Do we want to do better URLs for demos? Like webrtc.goinstant.com or something to that effect? cc/ @ianlivingstone

**Comment by colinmacdonald** [comment]
I can hand it off to @lgtml once the demo is merged to set it up like the maps demo with a proper URL.

**Comment by ntassone** [comment]
@byosko Here's what I came up with for the sticky banner for demos. I think it's probably better at the bottom where there's usually less visual noise. I find fixed to the bottom makes it look more like a demo than the top (where it kind of looks like a main-nav for the page). My demo's not running right now but this gives you an idea:

![image](https://f.cloud.github.com/assets/1572205/1903812/0415ae5e-7c87-11e3-883c-77eba34d6cd7.png)

**Comment by byosko** [comment]
Sign up free
Docs & API
Share with friends:

**Comment by byosko** [comment]
@colinmacdonald there's a broken image here: https://github.com/goinstant/webrtc

Also on github pages can we put a brief 1-2 sentence description of the repo above the code?

**Comment by byosko** [comment]
"The GoInstant WebRTC widget provides a drop-in, back-end free, video conferencing solution."

Let's do:

"The GoInstant WebRTC widget provides a drop-in, back-end free audio and video conferencing solution. It's the easiest way to add WebRTC into your application."
- Note: Maybe this goes above the code as per my previous comment?

**Comment by colinmacdonald** [comment]
Yeah, that image will be corrected when we make the repo public and the tests run on public travis.

I'll get someone with permissions to throw that description in.

**Comment by byosko** [comment]
"Sign up and build a GoInstant application today. You can learn more in our guides, and documentation"

go with:

"To use the WebRTC widget, sign up for a free GoInstant account. You can also learn more in our documentation. And check out the demo we've built using the WebRTC widget -- you can invite friends to join you in a video/audio conference."

-- sign up for a free GoInstant account = hyperlink
-- documentation = hyperlink right to the widget docs
-- check out the demo = hyperlink to the demo

**Comment by byosko** [comment]
GoRTC github:

"The GoRTC library glues together webrtc.js and GoInstant to offer video conferencing with no server deployment or configuration." -- I think we wrote a bit more for our docs, which we can include here. And maybe this belongs above the code?

Let's also add in separate lines:

To use GoRTC, you can sign up for a free GoInstant account. -- "sign up for a free GoInstant account" = hyperlink

Read the documentation on how GoRTC works. -- "Read the documentation" = hyperlink

Check out our demo leveraging GoRTC for easy audio/video conferencing. -- "Check out our demo" = hyperlink

**Comment by colinmacdonald** [comment]
so webrtc and gortc will have:

> To use the WebRTC widget, [sign up for a free GoInstant account](https://goinstant.com/signup). You can also learn more in our [documentation](https://developers.goinstant.com/v1/widgets/audio_and_video/index.html). And check out the [demo](http://webrtc.goinstant.com) we've built using the WebRTC widget -- you can invite friends to join you in a video/audio conference.

Then right below it will have the 3 links for signing up, the docs, and the demo?

**Comment by byosko** [comment]
@colinmacdonald let's do it on 3 separate lines so it breaks things up a bit. There are some minor differences b/w the two as well.

On WebRTC:

To use the WebRTC widget, sign up for a free GoInstant account. 

Read the documentation on how the WebRTC widget works.

Check out the demo using the WebRTC widget for easy audio and video conferencing.

On GoRTC:

To use GoRTC, you can sign up for a free GoInstant account.

Read the documentation on how GoRTC works.

Check out our demo leveraging GoRTC for easy audio and video conferencing.

**Comment by byosko** [comment]
I think the Github pages are done at this point. We've reviewed them numerous times.
